import { runtimeEnv } from "@/lib/loadEnv";
import { Metadata } from "next";

export const revalidate = 3600; // revalidate every hour
export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Impressum",
  // description: "Generated by create next app",
};

export default async function Imprint() {
  const baseUrl = runtimeEnv.CLOUDRON_APP_ORIGIN || "http://localhost:3000"; // Basis-URL
  const res = await fetch(baseUrl + "/api/imprint", {
    cache: "force-cache", // Erzwungener Cache
  }).catch(() => null);

  if (res == null || !res.ok) {
    return (
      <div>
        <h1>Impressum</h1>
        <p>Fehler beim Laden des Impressums.</p>
      </div>
    );
  }

  const data = await res.json();

  return (
    <div>
      <h1>Impressum</h1>
      <div dangerouslySetInnerHTML={{ __html: data.content }} />
    </div>
  );
}
